site_name: Cookiecutter Data Science
site_description: A project template and directory structure for Python data science projects.
site_favicon: favicon.ico
repo_url: https://git.equancy.io/cookiecutter-data-science-project
edit_uri: edit/master/docs/docs
copyright: Equancy freely inspired from DrivenData
#google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
